version: '3.8'

services:
  db:
    image: postgres:13  # Image officielle PostgreSQL (version 13 dans cet exemple)
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin  # Nom d'utilisateur de PostgreSQL
      POSTGRES_PASSWORD: admin  # Mot de passe pour l'utilisateur
      POSTGRES_DB: hch  # Nom de la base de données à créer
    ports:
      - "5432:5432"  # Expose le port 5432 pour accéder à PostgreSQL depuis l'hôte
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Monte un volume persistant
    networks:
      - my_network

volumes:
  postgres_data:  # Définit le volume persistant nommé "postgres_data"
    driver: local  # Utilise le driver local pour le volume

networks:
  my_network:  # Crée un réseau personnalisé si besoin
    driver: bridge
