version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.3-alpine
    container_name: postgres_local
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-hch}
    ports:
      - "5432:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-hch}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_local_data:
    driver: local
