version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.3-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin  # Nom d'utilisateur de PostgreSQL
      POSTGRES_PASSWORD: admin  # Mot de passe pour l'utilisateur
      POSTGRES_DB: hch  # Nom de la base de données à créer
    ports:
      - "5432:5432"  # Expose le port 5432 pour accéder à PostgreSQL depuis l'hôte
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Monte un volume persistant
    networks:
      - my_network

  backend:
    build:
      context: ../  # On suppose que Dockerfile est dans le dossier parent
      args:
        DATABASE_URL: postgres://admin:admin@db:5432/hch
    container_name: nest_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/hch
      SECRET_KEY: supersecretjwtkey
      NODE_ENV: production
      PORT: 3001
    ports:
      - "3001:3001"  # Expose le backend NestJS
    networks:
      - my_network

volumes:
  postgres_data:  # Définit le volume persistant nommé "postgres_data"
    driver: local

networks:
  my_network:  # Crée un réseau personnalisé si besoin
    driver: bridge
