services:
  db:
    image: postgis/postgis:13-3.3-alpine
    env_file:
      - ../.env
    environment:

      POSTGRES_USER: ${POSTGRES_USER} #superuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Ne pas exposer la base de données publiquement en production
    # Supprimez la section ports pour empêcher l'accès externe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  backend:
    build:
      context: ../
    restart: always
    depends_on:
      - db
    env_file:
      - ../.env
    environment:

      #RunTime(API)
      DATABASE_URL: ${DATABASE_URL}
      #Migrations: superuser
      ADMIN_DATABASE_URL: ${ADMIN_DATABASE_URL}
      
      SECRET_KEY: ${SECRET_KEY}
      NODE_ENV: ${NODE_ENV:-production}
    PORT: ${PORT}

  ports:
    - ${PORT}:${PORT}  # En prod, idéalement derrière un reverse proxy (nginx) et/ou lié à 127.0.0.1
  command: >
    sh -c "
      DATABASE_URL=$ADMIN_DATABASE_URL npx prisma migrate deploy &&
      node dist/main.js
    "
  networks:
    - my_network


volumes:
  postgres_data:
    driver: local

networks:
  my_network:
    driver: bridge