name: Deploy to VPS test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS via SSH
        run: |
          ssh -o StrictHostKeyChecking=no deploy@217.154.117.179 << 'EOF'
            cd /var/www/test/hch-back/docker
            git checkout main
            git pull
            docker compose --env-file ../.env -p hch_back_test up -d --build
          EOF
